### ISSUE TITLE
Design Document/ToDo List

### ISSUE THREAD

**Issue by VMSolidus** [DeltaV-Station/Perihelion#1]
Alright, now that I'm finally back home and can actually begin work on this project, here's my submission for the Perihelion design document. This list will serve as a guideline for what we need to do in order to make an English HRP server work correctly. The requirements for HRP are radically different from many design decisions that Wizden has made for SS14, and some may require making certain changes to core game code. As a whole, the purpose of an HRP server is to provide what is essentially a very advanced form of writers chat room, rather than an actual "Game" that someone can win. Therefore certain "Gamifications" need to be reworked or removed in order to better support this intended goal. 

The Hard Requirements are design elements that must be completed before an HRP server can be opened to the public. These are not optional, and some of them may be quite involved. A few of them I have worked on design documents for, but will require discussion on how they may be implemented.

Soft Requirements are those we do not explicitly require to launch an HRP server, but are helpful to have for the player experience. 

### **Hard Requirements**

- [ ] Removal/Rework of "Greentext" Antagonists 

The entire gameplay concept of the "Greentext" is antithetical to an HRP server. An HRP round cannot be "Won", and no effort should be made to encourage such playing to win behavior. Therefore a majority of the game's antagonists will need to be commented out or removed from rotation. The only antagonist that currently exists in the game which we can rework easily is the Traitor, which I'd like to invite an open ended discussion for what their new objectives should be. Since removing the Greentext itself is not easily done without touching Wizden's side of things, a temporary approach may be made whereby all objectives are automatically "Green" at the end of the round, provided the traitor is alive.

- [ ] Rework Traitors to have open-ended objectives with explicit RP directions. 

To give an example of a some open ended objectives, Kill/Maroon might be replaced with Poach/Recruit/Kill. With the goal being to meet with the target player, and attempt to convince them to join the Syndicate, or quit Nanotrasen. This is an explicitly RP oriented objective, whose solution comes from talking with your target and actually meaningfully interacting with them. Another objective might be to Infiltrate a certain department, that is, get yourself hired on to a specific department, so you can observe and steal company secrets. A traitor might be instructed to get themselves hired by the Security department. 

- [ ] Character Backstory/Exploitable Information(Employee Records, Medical Records, Blackmailable Records, Security Records)

I'll expand more upon this one with a separate design document. The gist of this is that in the character customization screen, the "Description" tab needs to be reworked as an Information tab, which will include the Description, as well as a character's Backstory. Backstory will be written in four different form fields, for each of the 4 different Exploitables. Employee Records will be readable by anyone who is a head of staff via a corporate records console. Medical Records will be readable by anyone with Medical access(they have to put an ID into a medical records computer, then they can read the records). Same with Security records, they can put an ID in a special computer, then read up on anyone's security records. 

The last one is Blackmailable information. Traitor players will be able to buy a laptop item that lets them search for, and read a character's blackmail information. The rules for this will be thus: By invoking a given character's blackmailable information, that character is temporarily considered a minor antagonist, and is expected to provide some assistance to the traitor in exchange for the traitor's silence. What form of assistance this may take is up to the two players, but generally should not include extreme crimes such as terrorism or murder. 

Only the player themself should be able to write what's in their character's backstory. They cannot be edited ingame, only in the lobby. 

- [ ] Create a Lore Document/Lore Wiki
- [ ] Write up Rules for the HRP server. 
- [ ] Rework to player slots/whitelist. 

This last one is very important. To prevent the server from being just a Clique, there needs to be a certain number of player slots explicitly set aside for non-whitelisted players. Rather than locking the server to new people when the player count is above 20, there needs to explicitly be slots set aside that can only be taken by people who aren't whitelisted, likely no more than 15 to 20 people. The main purpose of this would be to allow people who aren't whitelisted to come on the server and advertise themselves as a writer for the purpose of getting whitelisted. The standards for who is whitelisted should take into account people's skill in writing a character. That is, we should mainly consider the quality of people's ingame character sheets, and whether or not their character is a good fit for the server. 

### **Soft Requirements**

- [ ] #3
- [ ] Opt-In Sleeper Agent traitors, traitors that can spontaneously become traitors some significant amount of time during the round. Essentially, Midround traitor activations.
- [ ] Implement Aurora Station's Cryostasis system. Players need to be able to leave a round(and have their job specific equipment returned to the original department). Captain John Greytider needs to be able to join, leave via cryostasis, and then Jill Greytider can  join as the newly opened Captain role, and pick up John's shit at her captain's quarters.
- [ ] Implement leaving and rejoining rounds(as different character). Basically an extension of Cryostasis, you can leave a round via either permanent death or cryostasis, and then rejoin the round as a different character entirely. For obvious reasons, same rules as Ghost Roles apply, players cannot act on information they have learned from previous lifes. 
- [ ] Expanding visual character customization (I have a separate design document for this, and am actively working on it)
- Underclothes as Markings
- Tattoo/Barber shop ingame to change markings
- Toggleable Clothing States via a right click dropdown menu
- Prosthetic Limb sprites

**Comment by DebugOk** [comment]
Just a quick place to organize stuff that I'll set up later because I was randomly motivated to look at this again.

https://go.delta-v.org/perihelion
